### PR TITLE
Add TheOneProbe compatibility with no conflicts

### PR DESCRIPTION
**Pull request by Konlii**

### CODE REVIEW

**Comment by bl4ckscor3** [comment]
Didn't you intend to squash the commits?

**Comment by Konlii** [comment]
Isn't the option for that on your end when you actually merge the PR?

**Comment by bl4ckscor3** [comment]
Not as far as I can tell. For my PRs I've been squashing myself instead of the person merging it.

**Comment by bl4ckscor3** [comment]
Oh, yes it is. Just didn't see the dropdown menu. My bad!

**Pull request merged**
